"caplin-pub" = "v1:https://caplin-snapshots-goerli.erigon.network"
"erigon-v2-pub" = "v1:https://erigon-v2-snapshots-goerli.erigon.network"
"e2-v2-pub" = "v1:https://erigon2-v2-snapshots-goerli.erigon.network"
"e2-v1-pub" = "v1:https://erigon2-v1-snapshots-goerli.erigon.network"
"e2-v3-pub" = "v1:https://erigon2-v3-snapshots-goerli.erigon.network"
"e3-v1-pub" = "v1:https://erigon3-v1-snapshots-goerli.erigon.network"
"e3-v3-pub" = "v1:https://erigon3-v3-snapshots-goerli.erigon.network"
